name: bmi_calculator
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_name: "^0.0.1"

flutter_launcher_name:
  name: "BMI Calculator"

flutter:
  uses-material-design: true
